### ISSUE TITLE
Single temperature for high-core CPU's

### ISSUE THREAD

**Issue by to4ko** [Meliox/PVE-mods#8] opened 2023-07-17 19:03 UTC
Hi! 

Is it possible to modify script to get single number (Package id 0) readings on summary screen instead of 14?)

![image](https://github.com/Meliox/PVE-mods/assets/45161980/bc0f7d99-2cb5-4c4f-a8c7-c9cbcf503b3f)

**Comment by Meliox** [comment] 2023-07-17 19:08
Hello,
Should work if you change this line: https://github.com/Meliox/PVE-mods/blob/main/pve-mod-gui-temp.sh#L115C6-L115C21 to "Package id " instead.

**Comment by to4ko** [comment] 2023-07-17 19:17
> Hello, Should work if you change this line: https://github.com/Meliox/PVE-mods/blob/main/pve-mod-gui-temp.sh#L115C6-L115C21 to "Package id " instead.

i'm doing something wrong?

![image](https://github.com/Meliox/PVE-mods/assets/45161980/90f3072c-3f0b-4d4e-939b-d13c79296098)

**Comment by Meliox** [comment] 2023-07-17 19:20
I mean change it from: CPU_ITEM_PREFIX="Core " to   CPU_ITEM_PREFIX="Package
id ". However, the line indicate something is wrong in or around line 15.
https://github.com/Meliox/PVE-mods/blob/main/pve-mod-gui-temp.sh#L15

Den man. 17. jul. 2023 kl. 21.17 skrev Dmitry ***@***.***>:

**Comment by to4ko** [comment] 2023-07-17 19:30
@Meliox small one - how this empy space can be removed?

![image](https://github.com/Meliox/PVE-mods/assets/45161980/114b774c-6e3f-40f1-bb02-5bd84dbf1883)

**Comment by Meliox** [comment] 2023-07-17 19:36
This is not caused by the mod, hence, I would ask, or fill a bug, to the proxmox team.

Btw. If you want to change "Core 0" to "Package 0", then simply change this line: https://github.com/Meliox/PVE-mods/blob/main/pve-mod-gui-temp.sh#L116

Non-moded:
![image](https://github.com/Meliox/PVE-mods/assets/5264368/ff21ec37-6a45-47f6-b7b2-3c4fae72933f)

**Comment by to4ko** [comment] 2023-07-17 19:39
it;s strange - here is mine non-moded
![image](https://github.com/Meliox/PVE-mods/assets/45161980/967ef24c-8f89-4fa4-b62e-9743dd178be9)

**Comment by Meliox** [comment] 2023-07-17 19:40
Can you share your non-modded file for comparison?

**Comment by to4ko** [comment] 2023-07-17 19:44
attached
[pvemanagerlib_and_Nodes_pm.zip](https://github.com/Meliox/PVE-mods/files/12073330/pvemanagerlib_and_Nodes_pm.zip)

**Comment by Meliox** [comment] 2023-07-17 19:51
Thanks.
Ok, mine had some leftovers:
![image](https://github.com/Meliox/PVE-mods/assets/5264368/425ce7cd-d84d-4166-92cf-150148fecb2c)

So, I guess we can conclude that something in this section makes in unwanted behavior. 

https://github.com/Meliox/PVE-mods/blob/main/pve-mod-gui-temp.sh#L190

**Comment by eremem** [comment] 2023-07-19 18:57
@Meliox I doesn't really look like our bug. Regardless of the modified `height`, `bodyPadding` and the other properties, the actual height of the box must grow anyway due to the added temperature entries. The layout manager of ExtJS (the JS framework under the hood) doesn't seem to be able to vertically align the boxes if their heights differ.

**Comment by carlox97** [comment] 2023-11-02 00:58
I edited [Line 15 and 16](https://github.com/Meliox/PVE-mods/blob/main/pve-mod-gui-temp.sh#L115) to
`CPU_ITEM_PREFIX="Package id "`
`CPU_TEMP_CAPTION="CPU Package"`

[Line 233](https://github.com/Meliox/PVE-mods/blob/main/pve-mod-gui-temp.sh#L233) to
``tempStr = \`\${cpuTempCaption}:&nbsp;\${temp}&deg;C\`;\n\``

to get "CPU Package: 52°C"

and [Line 325](https://github.com/Meliox/PVE-mods/blob/main/pve-mod-gui-temp.sh#L325) to
``temps.push(\`Samsung&nbsp;\EVO&nbsp;\960:&nbsp;\${temp}&deg;C\`);\n\``

to get "Samsung EVO 960: 27.85°C"

![git](https://github.com/Meliox/PVE-mods/assets/31673755/1cf39c58-f1bf-4d0b-b64f-4f2352c16b14)

@Meliox do you think it's fine or it might cause problems? I've had none so far.

**Comment by Meliox** [comment] 2023-11-02 05:03
Looks great. It will not cause you any problems. You will need to modify the script again if this one is updated.

**Comment by Meliox** [comment] 2024-06-16 15:21
Implemented in #54 . Closing this

**Closed by Meliox** 2024-06-16 15:21 UTC
Labels: enhancement
